version: '2'
services:
    mvc:
        build:
            context: ECommMvc
            dockerfile: Dockerfile
        image: mvcapp
        restart: unless-stopped
        ports:
            - 8000:80
        links:
            - cache
            - db
        depends_on: 
            - db
            - cache
    cache:
        image: redis
        restart: unless-stopped
    db:
        image: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=postgres
